visualization:
  use_visdom: True
  visdom_port: 9000
  visdom_server: 'http://localhost'

  image:
    every: 10
    scale: 0.5

  use_tensorboard: False
  tensorboard_logdir: '../../../data/weights/segmentation/multiunet/tensorboard_log/'
  save_historgam: False

model:
  net: 'multiunet'
  image_size: None
  input_channels: 1
  model_classes: 4

dataset:
  train_images_path: '../../../data/dataset/train_images/'
  train_table_path: '../../../data/dataset/train.csv'
  test_images_path: ''
  test_table_path: ''
  shape: [-1, -1] #[width, height]
  validation_part: 0.2

train:
  optimizer: 'sgd'
  lr: 0.1
  weight_decay: 0.000000001

  loss: 'bce'

  epochs: 500
  batch_size: 4
  number_of_processes: 8

  augmentation: False

  save:
    model: '../../../data/weights/segmentation/multiunet/'
    every: 10
  load: False

  checkpoint:
    use: False
    model: '../../../data/weights/segmentation/multiunet/early_model-5.trh'
    optimizer: '../../../data/weights/segmentation/multiunet/early_optimize_state-5.trh'

logging:
  use_logger: False
  log_path: '../../../data/weights/segmentation/multiunet/log.txt'
  log_step: 1
