visualization:
  use_visdom: True
  visdom_port: 9000
  visdom_server: 'http://localhost'

  image:
    every: 10
    scale: 1

  use_tensorboard: False
  tensorboard_logdir: '../../../data/weights/segmentation/albunet/tensorboard_log/'
  save_historgam: False

model:
  net: 'unet'
  image_size: None
  input_channels: 1
  model_classes: 1

dataset:
  train_images_path: '../../../data/dataset/train_images/'
  train_table_path: '../../../data/dataset/train.csv'
  test_images_path: ''
  test_table_path: ''
  shape: [-1, -1] #[width, height]
  validation_part: 0.2

train:
  optimizer: 'adam'
  lr: 0.001
  weight_decay: 0.000000001

  loss: 'mse'
  dise_loss:
    use: True
    base_loss_coeff: 0.5
    dice_loss_coeff: 0.5

  epochs: 500
  batch_size: 16
  number_of_processes: 8

  augmentation: True

  save:
    model: '../../../data/weights/segmentation/albunet/'
    every: 10

  load: True
  load_optimizer: False

  checkpoint:
    use: False
    model: '../../../data/weights/segmentation/albunet/early_model-5.trh'
    optimizer: '../../../data/weights/segmentation/albunet/early_optimize_state-5.trh'

logging:
  use_logger: False
  log_path: '../../../data/weights/segmentation/albunet/log.txt'
  log_step: 1
